# Generated by Django 2.1 on 2018-11-22 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iam', '0002_localuser_default_cred'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='credential',
            name='is_default',
        ),
    ]
