# Generated by Django 2.1 on 2019-01-08 00:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iam', '0003_auto_20190106_1402'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='localuser',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
    ]
