# Generated by Django 2.1 on 2019-01-08 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iam', '0003_auto_20190106_1402'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='localgroup',
            options={'ordering': ['name'], 'permissions': (('edit_groups', 'Create and edit groups'), ('edit_hosts', 'Create and edit hosts'), ('edit_playbooks', 'Edit playbooks'), ('edit_tasks', 'Edit tasks'), ('edit_roles', 'Edit roles'), ('execute_jobs', 'Execute jobs'), ('view_job_history', 'View job history'), ('edit_files', 'Create and edit files'), ('edit_users', 'Create and edit users'), ('edit_user_groups', 'Create and edit user groups'), ('edit_user_files', 'Create and edit user files'), ('edit_permissions', 'Edit user group permissions'), ('edit_preferences', 'Edit preferences'), ('edit_projects', 'Edit projects'))},
        ),
        migrations.AlterModelOptions(
            name='localuser',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
    ]
