# Generated by Django 2.1 on 2019-01-09 00:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iam', '0004_auto_20190108_0017'),
        ('iam', '0005_auto_20190108_2032'),
    ]

    operations = [
    ]
