# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-28 16:15
from __future__ import unicode_literals

from django.db import migrations
from django.contrib.auth.management import create_permissions


def add_user_groups(apps, schema_editor):

    groups = {
        'Project Admins': [
            'edit_projects',
            'edit_users',
            'edit_user_groups'
        ],
        'User Admins': [
            'edit_permissions'
        ],

        'System Admins': [
            'edit_projects',
            'edit_permissions'
        ]

    }

    group_class = apps.get_model('auth', 'Group')

    groupdata_class = apps.get_model('iam', 'GroupData')

    permission_class = apps.get_model('auth', 'Permission')

    for app_config in apps.get_app_configs():
        app_config.models_module = True
        create_permissions(app_config, apps=apps, verbosity=0)
        app_config.models_module = None

    for group_name in groups:

        group, created = group_class.objects.get_or_create(name=group_name)

        groupdata, created = groupdata_class.objects.get_or_create(group=group)

        groupdata.editable = False

        groupdata.save()

        for permission in groups[group_name]:

            perm = permission_class.objects.get(codename=permission)

            group.permissions.add(perm)


class Migration(migrations.Migration):

    dependencies = [
        ('iam', '0011_auto_20170902_1658'),
    ]

    operations = [
        migrations.RunPython(add_user_groups)
    ]
