# Generated by Django 2.1 on 2019-03-23 17:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import main.extras.mixins


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('description', models.TextField(blank=True, max_length=256)),
                ('playbooks', models.TextField(default='[]', max_length=65536)),
                ('roles', models.TextField(default='[]', max_length=65536)),
                ('can_edit_playbooks', models.ManyToManyField(related_name='can_edit_playbooks', to=settings.AUTH_USER_MODEL)),
                ('can_edit_roles', models.ManyToManyField(related_name='can_edit_roles', to=settings.AUTH_USER_MODEL)),
                ('can_edit_tasks', models.ManyToManyField(related_name='can_edit_tasks', to=settings.AUTH_USER_MODEL)),
                ('can_edit_variables', models.ManyToManyField(related_name='can_edit_variables', to=settings.AUTH_USER_MODEL)),
                ('can_run_playbooks', models.ManyToManyField(related_name='can_run_playbooks', to=settings.AUTH_USER_MODEL)),
                ('can_run_tasks', models.ManyToManyField(related_name='can_run_tasks', to=settings.AUTH_USER_MODEL)),
                ('host_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.Group')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
            bases=(models.Model, main.extras.mixins.RESTfulModelMixin),
        ),
    ]
