# Generated by Django 2.1 on 2019-01-06 14:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['name']},
        ),
        migrations.RemoveField(
            model_name='project',
            name='can_edit_playbooks',
        ),
        migrations.AddField(
            model_name='project',
            name='can_edit_playbooks',
            field=models.ManyToManyField(related_name='can_edit_playbooks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='project',
            name='can_edit_roles',
        ),
        migrations.AddField(
            model_name='project',
            name='can_edit_roles',
            field=models.ManyToManyField(related_name='can_edit_roles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='project',
            name='can_edit_tasks',
        ),
        migrations.AddField(
            model_name='project',
            name='can_edit_tasks',
            field=models.ManyToManyField(related_name='can_edit_tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='project',
            name='can_edit_variables',
        ),
        migrations.AddField(
            model_name='project',
            name='can_edit_variables',
            field=models.ManyToManyField(related_name='can_edit_variables', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='project',
            name='can_run_playbooks',
        ),
        migrations.AddField(
            model_name='project',
            name='can_run_playbooks',
            field=models.ManyToManyField(related_name='can_run_playbooks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='project',
            name='can_run_tasks',
        ),
        migrations.AddField(
            model_name='project',
            name='can_run_tasks',
            field=models.ManyToManyField(related_name='can_run_tasks', to=settings.AUTH_USER_MODEL),
        ),
    ]
