# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-17 14:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_groupdata'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='groupdata',
            options={'permissions': (('edit_groups', 'Can create and edit groups'), ('edit_hosts', 'Can create and edit hosts'), ('edit_playbooks', 'Can edit playbooks'), ('edit_tasks', 'Can edit tasks'), ('execute_jobs', 'Can execute jobs'), ('edit_files', 'Can create and edit files'), ('edit_users', 'Can create and edit users'), ('edit_user_groups', 'Can create and edit user groups'))},
        ),
        migrations.AddField(
            model_name='groupdata',
            name='editable',
            field=models.BooleanField(default=True),
        ),
    ]
