# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-31 19:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_create_user_groups'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credential',
            name='rsa_key',
            field=models.TextField(blank=True, max_length=2048),
        ),
    ]
