# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-27 18:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preferences', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='value',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
