# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-29 16:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        ('inventory', '0004_auto_20170817_1455'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('description', models.TextField(blank=True, max_length=256)),
                ('roles', models.TextField(default=b'[]', max_length=1024)),
                ('host_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Group')),
                ('user_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.Group')),
            ],
        ),
    ]
