# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-05 02:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='execute_jobs',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='execute_jobs', to='auth.Group'),
        ),
        migrations.AlterField(
            model_name='project',
            name='inventory_admins',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inventory_admins', to='auth.Group'),
        ),
        migrations.AlterField(
            model_name='project',
            name='runner_admins',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='runner_admins', to='auth.Group'),
        ),
    ]
