# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-05 22:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20170905_0237'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='playbooks',
            field=models.TextField(default=b'[]', max_length=65536),
        ),
        migrations.AlterField(
            model_name='project',
            name='roles',
            field=models.TextField(default=b'[]', max_length=65536),
        ),
    ]
