# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-06 17:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20170905_2215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='execute_jobs',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='execute_jobs', to='auth.Group'),
        ),
        migrations.AlterField(
            model_name='project',
            name='host_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.Group'),
        ),
        migrations.AlterField(
            model_name='project',
            name='inventory_admins',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inventory_admins', to='auth.Group'),
        ),
        migrations.AlterField(
            model_name='project',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='project',
            name='runner_admins',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='runner_admins', to='auth.Group'),
        ),
    ]
