# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-28 16:15
from __future__ import unicode_literals

from django.db import migrations
from django.contrib.auth.hashers import make_password


def add_admin_user(apps, schema_editor):

    user_class = apps.get_model('auth', 'User')

    user, created = user_class.objects.get_or_create(username='admin', is_superuser=True)

    user.password = make_password('admin')

    user.save()


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20170828_1509'),
    ]

    operations = [
        migrations.RunPython(add_admin_user)
    ]
