# Generated by Django 2.1 on 2019-03-23 17:56

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import main.extras.mixins


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('description', models.TextField(blank=True, max_length=256)),
            ],
            options={
                'ordering': ['name'],
            },
            bases=(models.Model, main.extras.mixins.RESTfulModelMixin),
        ),
        migrations.CreateModel(
            name='Variable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=128, validators=[django.core.validators.RegexValidator(inverse_match=True, message='Key names cannot contain "-"', regex='\\-')])),
                ('value', models.CharField(max_length=1024)),
            ],
            options={
                'ordering': ['key'],
            },
            bases=(models.Model, main.extras.mixins.RESTfulModelMixin),
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('node_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='inventory.Node')),
                ('config', models.BooleanField(default=False)),
                ('children', models.ManyToManyField(blank=True, to='inventory.Group')),
            ],
            bases=('inventory.node',),
        ),
        migrations.CreateModel(
            name='Host',
            fields=[
                ('node_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='inventory.Node')),
                ('facts', models.TextField(default='{}', max_length=65353)),
            ],
            bases=('inventory.node',),
        ),
        migrations.AddField(
            model_name='variable',
            name='node',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Node'),
        ),
        migrations.AlterUniqueTogether(
            name='variable',
            unique_together={('key', 'node')},
        ),
        migrations.AddField(
            model_name='group',
            name='members',
            field=models.ManyToManyField(blank=True, to='inventory.Host'),
        ),
    ]
