# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-30 02:44
from __future__ import unicode_literals

from django.db import migrations


def create_group_all(apps, schema_editor):

    group_class = apps.get_model('inventory', 'Group')

    group_class.objects.get_or_create(name='all')


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_group_all)
    ]
