# Generated by Django 2.1 on 2018-11-02 03:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_auto_20180728_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='facts',
            field=models.TextField(default='{}', max_length=65353),
        ),
        migrations.AlterField(
            model_name='variable',
            name='key',
            field=models.CharField(max_length=128, validators=[django.core.validators.RegexValidator(inverse_match=True, message='Key names cannot contain "-"', regex='\\-')]),
        ),
    ]
