# Generated by Django 2.1 on 2019-01-06 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_auto_20181102_0303'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='host',
            options={'ordering': ['name']},
        ),
    ]
