# Generated by Django 2.1 on 2019-01-19 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_auto_20190106_1402'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='variable',
            options={'ordering': ['key']},
        ),
        migrations.AddField(
            model_name='group',
            name='config',
            field=models.BooleanField(default=False),
        ),
    ]
