# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-03 03:18
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdHocTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hosts', models.CharField(max_length=64)),
                ('module', models.CharField(max_length=32)),
                ('arguments', models.TextField(blank=True, max_length=1024)),
                ('become', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='PlaybookArgs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playbook', models.CharField(max_length=64)),
                ('tags', models.CharField(blank=True, max_length=64, null=True)),
                ('skip_tags', models.CharField(blank=True, max_length=64, null=True)),
                ('subset', models.CharField(blank=True, max_length=64, null=True)),
                ('extra_vars', models.CharField(blank=True, max_length=128, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Runner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_running', models.BooleanField(default=False)),
                ('type', models.CharField(choices=[(b'playbook', b'playbook'), (b'adhoc', b'adhoc'), (b'gather_facts', b'gather_facts')], max_length=16)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=128)),
                ('pid', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(max_length=32)),
                ('message', models.CharField(blank=True, max_length=1024, null=True)),
                ('tags', models.CharField(blank=True, max_length=64, null=True)),
                ('skip_tags', models.CharField(blank=True, max_length=64, null=True)),
                ('extra_vars', models.CharField(blank=True, max_length=128, null=True)),
                ('subset', models.CharField(blank=True, max_length=1024, null=True)),
                ('check', models.BooleanField()),
                ('stats', models.TextField(blank=True, max_length=4096, null=True)),
                ('failed_hosts', models.TextField(blank=True, max_length=4096, null=True)),
                ('cred', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Credential')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RunnerPlay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('hosts', models.CharField(max_length=64)),
                ('become', models.BooleanField()),
                ('gather_facts', models.BooleanField(default=False)),
                ('host_count', models.IntegerField(null=True)),
                ('failed_count', models.IntegerField(default=0)),
                ('runner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='runner.Runner')),
            ],
        ),
        migrations.CreateModel(
            name='RunnerResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(max_length=64)),
                ('status', models.CharField(max_length=32)),
                ('message', models.TextField(blank=True, max_length=32768, null=True)),
                ('response', models.TextField(default=b'{}', max_length=65536)),
            ],
        ),
        migrations.CreateModel(
            name='RunnerTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('module', models.CharField(blank=True, max_length=64, null=True)),
                ('host_count', models.IntegerField(null=True)),
                ('is_handler', models.BooleanField()),
                ('runner_play', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='runner.RunnerPlay')),
            ],
        ),
        migrations.AddField(
            model_name='runnerresult',
            name='runner_task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='runner.RunnerTask'),
        ),
        migrations.AlterUniqueTogether(
            name='playbookargs',
            unique_together=set([('playbook', 'tags', 'subset', 'skip_tags', 'extra_vars')]),
        ),
    ]
