# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-30 02:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('runner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='runner',
            name='cred',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Credential'),
        ),
        migrations.AddField(
            model_name='runner',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='playbookargs',
            unique_together=set([('playbook', 'tags', 'subset', 'skip_tags', 'extra_vars')]),
        ),
    ]
