# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-07 04:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='runnertask',
            name='is_running',
            field=models.BooleanField(default=True),
        ),
    ]
