# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-17 14:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('runner', '0004_auto_20170817_1410'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adhoctask',
            options={},
        ),
        migrations.AlterModelOptions(
            name='job',
            options={},
        ),
        migrations.AlterModelOptions(
            name='playbookargs',
            options={},
        ),
    ]
