# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-27 02:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runner', '0005_auto_20170817_1455'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='folder',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
