# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-30 00:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runner', '0006_job_folder'),
    ]

    operations = [
        migrations.AddField(
            model_name='playbookargs',
            name='folder',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
