# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-03 17:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runner', '0010_auto_20180515_0121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adhoctask',
            name='hosts',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
