# Generated by Django 2.1 on 2019-01-22 00:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('iam', '0007_auto_20190119_0126'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdHocTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hosts', models.CharField(blank=True, max_length=64)),
                ('module', models.CharField(max_length=32)),
                ('arguments', models.TextField(blank=True, max_length=1024)),
                ('become', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_running', models.BooleanField(default=False)),
                ('type', models.CharField(choices=[('playbook', 'playbook'), ('adhoc', 'adhoc'), ('gather_facts', 'gather_facts')], max_length=16)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('path', models.CharField(blank=True, max_length=256, null=True)),
                ('pid', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(max_length=32)),
                ('message', models.CharField(blank=True, max_length=1024, null=True)),
                ('tags', models.CharField(blank=True, max_length=64, null=True)),
                ('skip_tags', models.CharField(blank=True, max_length=64, null=True)),
                ('extra_vars', models.CharField(blank=True, max_length=128, null=True)),
                ('subset', models.CharField(blank=True, max_length=1024, null=True)),
                ('check', models.BooleanField()),
                ('stats', models.TextField(blank=True, max_length=4096, null=True)),
                ('cred', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='iam.Credential')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Play',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('hosts', models.CharField(max_length=64)),
                ('become', models.BooleanField()),
                ('gather_facts', models.BooleanField(default=False)),
                ('message', models.CharField(blank=True, max_length=1024, null=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='runner.Job')),
            ],
        ),
        migrations.CreateModel(
            name='PlaybookArgs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=256)),
                ('tags', models.CharField(blank=True, max_length=64, null=True)),
                ('skip_tags', models.CharField(blank=True, max_length=64, null=True)),
                ('subset', models.CharField(blank=True, max_length=64, null=True)),
                ('extra_vars', models.CharField(blank=True, max_length=128, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(max_length=64)),
                ('status', models.CharField(max_length=32)),
                ('message', models.TextField(blank=True, max_length=32768, null=True)),
                ('response', models.TextField(default='{}', max_length=65536)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('module', models.CharField(blank=True, max_length=64, null=True)),
                ('is_handler', models.BooleanField()),
                ('is_running', models.BooleanField(default=False)),
                ('play', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='runner.Play')),
            ],
        ),
        migrations.AddField(
            model_name='result',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='runner.Task'),
        ),
        migrations.AlterUniqueTogether(
            name='playbookargs',
            unique_together={('path', 'tags', 'subset', 'skip_tags', 'extra_vars')},
        ),
    ]
