# Generated by Django 2.1 on 2019-01-22 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runner', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='path',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='playbookargs',
            name='path',
            field=models.CharField(max_length=512),
        ),
    ]
