# Generated by Django 2.1 on 2019-02-27 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runner', '0002_auto_20190122_0044'),
    ]

    operations = [
        migrations.AddField(
            model_name='adhoctask',
            name='name',
            field=models.CharField(default='temp', max_length=64),
            preserve_default=False,
        ),
    ]
