# Generated by Django 2.1 on 2019-02-27 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runner', '0003_adhoctask_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adhoctask',
            name='name',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
