# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-17 14:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('runner', '0003_auto_20170816_1723'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adhoctask',
            options={'permissions': (('edit_tasks', 'Can edit tasks'),)},
        ),
        migrations.AlterModelOptions(
            name='playbookargs',
            options={'permissions': (('edit_playbooks', 'Can edit playbooks'),)},
        ),
    ]
