# Generated by Django 2.1 on 2019-02-28 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runner', '0004_auto_20190227_1409'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='created_on',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='path',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='job',
            name='extra_vars',
        ),
        migrations.RemoveField(
            model_name='job',
            name='is_running',
        ),
        migrations.RemoveField(
            model_name='job',
            name='skip_tags',
        ),
        migrations.RemoveField(
            model_name='job',
            name='subset',
        ),
        migrations.RemoveField(
            model_name='job',
            name='tags',
        ),
        migrations.AddField(
            model_name='job',
            name='parameters',
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='type',
            field=models.CharField(choices=[('playbook', 'playbook'), ('task', 'task'), ('facts', 'facts')], max_length=16),
        ),
    ]
