# Generated by Django 2.1 on 2019-03-01 03:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('runner', '0005_auto_20190228_1841'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='type',
            new_name='job_type',
        ),
    ]
