# Generated by Django 2.1 on 2019-03-01 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('runner', '0006_auto_20190301_0319'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='stats',
            new_name='statistics',
        ),
    ]
