# Generated by Django 2.1 on 2019-03-03 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runner', '0008_auto_20190303_0220'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='subset',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
