# Generated by Django 2.1 on 2019-03-13 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runner', '0009_job_subset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='statistics',
            field=models.TextField(default='', max_length=4096),
        ),
    ]
