# Generated by Django 2.1 on 2019-03-13 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runner', '0010_auto_20190313_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='statistics',
            field=models.TextField(default='{}', max_length=4096),
        ),
    ]
