# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-30 02:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Credential',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32)),
                ('is_shared', models.BooleanField(default=False)),
                ('username', models.CharField(max_length=32)),
                ('password', models.CharField(blank=True, max_length=64)),
                ('rsa_key', models.CharField(blank=True, max_length=128)),
                ('sudo_user', models.CharField(blank=True, max_length=32)),
                ('sudo_pass', models.CharField(blank=True, max_length=64)),
                ('ask_pass', models.BooleanField(default=True)),
                ('ask_sudo_pass', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('timezone', models.CharField(max_length=64)),
                ('default_cred', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='iam.Credential')),
            ],
        ),
        migrations.AddField(
            model_name='credential',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='credential',
            unique_together=set([('user', 'title')]),
        ),
    ]
