# Generated by Django 2.1 on 2018-11-02 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iam', '0012_create_user_groups_2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupdata',
            name='description',
            field=models.CharField(default='', max_length=256),
        ),
    ]
