# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-30 02:43
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('description', models.TextField(blank=True, max_length=256)),
                ('children', models.ManyToManyField(blank=True, to='inventory.Group')),
            ],
        ),
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('description', models.TextField(blank=True, max_length=256)),
                ('facts', models.TextField(blank=True, max_length=65353)),
            ],
        ),
        migrations.CreateModel(
            name='Variable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=32, validators=[django.core.validators.RegexValidator(inverse_match=True, message=b'Key names cannot contain "-"', regex=b'\\-')])),
                ('value', models.CharField(max_length=1024)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.Group')),
                ('host', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.Host')),
            ],
        ),
        migrations.AddField(
            model_name='group',
            name='members',
            field=models.ManyToManyField(blank=True, to='inventory.Host'),
        ),
        migrations.AlterUniqueTogether(
            name='variable',
            unique_together=set([('key', 'group'), ('key', 'host')]),
        ),
    ]
