# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-17 14:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_auto_20170816_1438'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={},
        ),
        migrations.AlterModelOptions(
            name='host',
            options={},
        ),
    ]
