# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-01 23:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_auto_20170817_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='facts',
            field=models.TextField(default=b'{}', max_length=65353),
        ),
    ]
