---
- name: 0 Test playbook
  gather_facts: True
  hosts: all
  become: no

  tasks:

    - name: Test filecopy
      copy: content="{{ ansible_hostname }}"
            dest=/tmp/test1
      notify:
        - Erase test1

    - name: Test with items
      lineinfile: line="{{ item }}"
                  create=yes
                  dest=/tmp/test2
      with_items:
          - "Hello, assholes"
          - "Goodbye, assholes"
      notify:
          - Erase test2

    - name: Start mongos
      service: name=mongos
               state=started
      when: "'app-mongos' in group_names"

    - include: /opt/ans_data/install_vi.yml
      when: "'app-mongos' in group_names"

  handlers:

    - name: Erase test1
      file: path=/tmp/test1
            state=absent

    - name: Erase test2
      file: path=/tmp/test2
            state=absent
