---
- name: 0 Test playbook
  gather_facts: False
  hosts: all
  become: False
  
  tasks:
    - name: Check hostname
      command: hostname

    - name: Test filecopy
      copy: content="Hello world"
            dest=/tmp/playbook_test

    - name: Delete temp file
      file: path=/tmp/playbook_test
            state=absent

    - name: Test with items
      lineinfile: line="{{ item }}"
                  create=yes
                  dest=/tmp/test_2
      with_items:
          - "Hello, assholes"
          - "Goodbye, assholes"

    - name: Read file
      command: cat /tmp/test_2

    - name: Delete temp2
      file: path=/tmp/test_2
            state=absent

