---
- name: 0 Test playbook
  gather_facts: no
  hosts: all
  become: yes
  
  vars:
      var_file: /opt/ans_data/variables.yml
      play_file: /opt/ans_data/install_vi.yml

  tasks:

    #- include_vars: '{{ var_file }}'
 
    #- include: '{{ play_file }}'
    #  when: "'app-mongos' in group_names"
 
    - name: Delete test file
      file: path=/tmp/test_file
            state=absent
      notify:
        - Create test file

    #- name: Test with items
    #  lineinfile: line="{{ item }}"
    #              create=yes
    #              dest=/tmp/test2
    #  with_items:
    #      - "Hello, assholes"
    #      - "Goodbye, assholes"
    #  notify:
    #      - Erase test2


    #- name: Create temp angular folder
    #  file: path=/tmp/angular
    #        state=directory
    #        mode=0755
    
    #- name: Extract angular archive
    #  unarchive: src=/opt/ans_data/angularjs.tar.gz
    #             dest=/tmp/angular
    #             directory_mode=0755
    #             mode=0644

    #- name: Start mongos
    #  service: name=mongos
    #           state=started
    #  when: "'app-mongos' in group_names"

  handlers:

    - name: Create test file
      copy: dest=/tmp/test_file
            content='battuta test file'

    - name: Erase test2
      file: path=/tmp/test2
            state=absent
