---
- name: Basic Settings
  gather_facts: False
  hosts: frotaweb:!znh
  become: yes
  
  tasks:

    - name: Copy current user rsa.pub to server
      authorized_key: user={{ ansible_ssh_user }}
                      key="{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
                      state=present

