---
- name: Deploy Websocket
  hosts: m2m-websocket
  become: yes
  vars:
      mode: deploy
  
  roles:
    - role: nodejs 
      when: mode == 'install'
      
    - role: m2m-websocket
    
    - role: m2m-watchdog
      config: 'service'
      when: (mode == 'install') or (mode == 'config')
