---
- name: Deploy SSO API
  hosts: m2m-sso-api
  become: yes
  vars:
      mode: deploy
  
  roles:
    - role: nodejs 
      when: mode == 'install'
      
    - role: m2m-sso-api
    
    - role: m2m-watchdog
      config: 'service'
      when: mode == 'install'
