---
- name: Populate hosts file
  gather_facts: False
  hosts: poc_aws
  become: yes

  vars:
    hosts:
      - 10.10.1.10  zn1-mysql0
      - 10.10.1.11  zn1-rabbit-av0
      - 10.10.1.12  zn1-worker-ra
      - 10.10.1.13  zn1-worker-rv
      - 10.10.1.14  zn1-worker-aa
      - 10.10.1.15  zn1-redis0
      - 10.10.1.16  zn1-rs0-a
      - 10.10.1.17  zn1-rs0-d0
      - 10.10.1.18  zn1-rs0-d1
      - 10.10.1.19  zn1-rs1-a
      - 10.10.1.20  zn1-rs1-d0
      - 10.10.1.21  zn1-rs1-d1
      - 10.10.1.22  zn1-rs2-a
      - 10.10.1.23  zn1-rs2-d0
      - 10.10.1.24  zn1-rs2-d1
      - 10.10.1.25  zn1-nginx0
      - 10.10.1.26  zn1-api0
      - 10.10.1.27  zn1-websocket0
      - 10.10.1.28  sso-admin-api0
      - 10.10.1.29  sso-api0
      - 10.10.1.30  sso-nginx0
      - 10.10.1.31  sso-report0
      - 10.10.1.32  sso-mysql0
      - 10.10.1.33  zn1-gwa1
      - 10.10.1.34  zn1-worker-a1
      - 10.10.1.35  zn1-worker-v1
      - 10.10.1.36  zn1-worker-s1
      - 10.10.1.37  zn1-worker-e1
      - 10.10.1.38  zn1-gwa2
      - 10.10.1.39  zn1-worker-a2
      - 10.10.1.40  zn1-worker-v2
      - 10.10.1.41  zn1-worker-s2
      - 10.10.1.42  zn1-worker-e2
      - 10.10.1.43  zn1-gwa3
      - 10.10.1.44  zn1-worker-a3
      - 10.10.1.45  zn1-worker-v3
      - 10.10.1.46  zn1-worker-s3
      - 10.10.1.47  zn1-worker-e3
      - 10.10.1.48  zn1-gwa4
      - 10.10.1.49  zn1-worker-a4
      - 10.10.1.50  zn1-worker-v4
      - 10.10.1.51  zn1-worker-s4
      - 10.10.1.52  zn1-worker-e4
      - 10.10.1.53  zn1-gwa5
      - 10.10.1.54  zn1-worker-a5
      - 10.10.1.55  zn1-worker-v5
      - 10.10.1.56  zn1-worker-s5
      - 10.10.1.57  zn1-worker-e5
      - 10.10.1.58  zn1-gwa6
      - 10.10.1.59  zn1-worker-a6
      - 10.10.1.60  zn1-worker-v6
      - 10.10.1.61  zn1-worker-s6
      - 10.10.1.62  zn1-worker-e6
      - 10.10.1.63  zn1-gwa7
      - 10.10.1.64  zn1-worker-a7
      - 10.10.1.65  zn1-worker-v7
      - 10.10.1.66  zn1-worker-s7
      - 10.10.1.67  zn1-worker-e7
      - 10.10.1.68  zn1-gwa8
      - 10.10.1.69  zn1-worker-a8
      - 10.10.1.70  zn1-worker-v8
      - 10.10.1.71  zn1-worker-s8
      - 10.10.1.72  zn1-worker-e8
      - 10.10.1.73  zn1-gwa9
      - 10.10.1.74  zn1-worker-a9
      - 10.10.1.75  zn1-worker-v9
      - 10.10.1.76  zn1-worker-s9
      - 10.10.1.77  zn1-worker-e9


  tasks:
  - name: Add hosts to /etc/hosts
    lineinfile: dest=/etc/hosts
                line="{{ item }}"
                create=yes
                insertafter=EOF
    with_items: "{{ hosts }}"

  - name: Set hostname
    copy: content={{inventory_hostname}}
          dest=/etc/hostname
