---
- name: Update m2m-worker properties
  gather_facts: no
  hosts: m2m-worker:m2m-worker-rep:m2m-worker-sin:!znh
  become: yes

  tasks:
    - name: Update worker properties
      replace: dest=/opt/{{ item }}/config.properties
               regexp="^clientes=.*"
               replace="clientes={{ clientes }}"

      when: "'{{ item }}' in group_names"
      notify:
        - Restart {{ item }}
      with_items:
        - m2m-worker
        - m2m-worker-rep
        - m2m-worker-sin

  handlers:
    - name: Restart m2m-worker
      service: name=m2m-worker state=restarted

    - name: Restart m2m-worker-rep
      service: name=m2m-worker-rep state=restarted

    - name: Restart m2m-worker-sin
      service: name=m2m-worker-sin state=restarted